### ISSUE TITLE
Nuxt Support

### ISSUE THREAD

**Issue by MikeJWms** [ditdot-dev/vue-flow-form#152]
First of all, thank you to the developers for making such a beautiful form component.

**Is your feature request related to a problem? Please describe.**
Using vue-flow-form following the recommended npm integration is not possible because nuxt will try to render it on the server, and the component has client dependencies. `navigator is not defined` is the problem I kept running into when trying to get this to work.

**Describe the solution you'd like**
I'd love to see a clear guide on how to use vue-flow-form with nuxt.

**Describe alternatives you've considered**
I spent an afternoon trying to wrap vue-flow-form in a plugin and disabling ssr for it in nuxt.config. The problem I ran into was using QuestionModel, QuestionType, etc... These models seem to have client side dependencies and I couldn't figure out how to make this all work with Nuxt.

**Comment by spinn** [comment]
Thank you for your feedback and your bug report. It's true that the current version depended on some global variables that are only defined when running in the browser, but this has been fixed in commit 2424cf04df101351fe57416d3cbb12992c7081fc

This fix is not yet present in the NPM version, but we'll publish a new version soon.

Another thing I noticed when using with Nuxt is that you must import the CSS a bit differently:

```
@import 'node_modules/@ditdot-dev/vue-flow-form/dist/vue-flow-form.css';
```
