### ISSUE TITLE
How could I put a question with a custom input?

### ISSUE THREAD

**Issue by miguelgarces123** [ditdot-dev/vue-flow-form#199]
I would like to use [v-select](https://vue-select.org/) to override the select type you have in the package, but I don't see a way to incorporate custom input.

Do you already have this option available?.

Great this package, thanks!

**Comment by spinn** [comment]
Hi @miguelgarces123,

Vue Flow Form doesn't support this by default although custom input types are something we'd like to add in a future version. To do this now, you'd have to clone the GitHub project and create a custom input type by extending src/components/QuestionTypes/BaseType.vue, and then adding that custom question type to src/models/QuestionModel.js. Also make sure you're using Vue Flow Form v1.1.7 since Vue Select doesn't seem to be supporting Vue 3 for now (there does seem to be a fork that does, though).
