### ISSUE TITLE
Keyboard & accessibility navigation issues

### ISSUE THREAD

**Issue by arpadgabor** [ditdot-dev/vue-flow-form#96]
Just checked out your questionnaire demo, there are some (rather serious) navigation issues.

1. Pressing tab does not focus the buttons (don't use `<a>` tags, use `<button type="button">`)
2. Multi-select is also not accessible.
3. Up/down arrow are also only accessible with a mouse, keyboard arrows should also send you to the next/prev section.
4. Sometimes tab takes me to the next section instead of navigating the current section.

e.g.
```
<a href="#" role="button" aria-label="Press to continue" class="animate fade-in-up f-enter">
  <div class="o-btn-action"><span>OK</span></div><span class="f-enter-desc">Press ENTER</span>
</a>
```
should be
```
<div class="flex">
  <button type="button" class="o-btn-action">
    OK
  </button>
  <span>
    Press <span class="f-enter-desc uppercase">Enter</span>
  </span>
</div>
```

Also for accessibility, please style the `:focus` state of everything that is focusable, so a keyboard user will know where he is situated on the screen.

![image](https://user-images.githubusercontent.com/9270494/92481503-1cbf5380-f1ef-11ea-81d5-422dd3075447.png)
As you can see, chrome also detects buttons as `generic` and `non-keyboard focusable`.

Also a small note: screen readers will read ENTER as E N T E R, while Enter with uppercase css styling will be read like normal.

**Comment by EkaterinaVu** [comment]
Thank you for your feedback, we made a few modifications regarding accessibility and keyboard navigation based on your suggestions:

- Main step controls are now buttons 
- Fixed an issue regarding getting back to focus with tab on some questions 
- Added additional element focus styles 
- Removed upper case from HTML

Related commit links: 

-  https://github.com/ditdot-dev/vue-flow-form/commit/a59f30d842f3af0ca76d5f29c0ee46d52cc8a141
- https://github.com/ditdot-dev/vue-flow-form/commit/733e566bb16de2d7b562615bf31829d9fae377fc
- https://github.com/ditdot-dev/vue-flow-form/commit/f863077b4688dcca7565157f022bfc3fe3e3006e 

Your other suggestions are all valid, and where discussed in the development process. The current tab and focus behavior is intentional and is the essential concept of this form experience. This is a question per question form and the objective is to reduce unnecessary interaction.

The tab is used to move the focus from field to field, like in standard forms. On MultipleChoice questions, you can select/unselect your options by pressing the keys on the keyboard, and there are multiple helper text options for explanation purposes that can be used.
